<a href="https://colab.research.google.com/github/OG810/Machine-Learning-Algorithms/blob/main/PCA_step_by_step_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
np.random.seed(23) #This line sets the random seed for NumPy's random number generator. Setting the seed ensures that if you run the code again, you'll get the same random numbers. This is useful for reproducibility.
mu_vec1=np.array([0,0,0]) ## centralizing the mean.
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)
## Here, we define the mean vector (mu_vec1) and covariance matrix (cov_mat1) for the first set of samples. The np.random.multivariate_normal function generates random samples from a multivariate normal distribution. In this case, it generates 20 samples with mean mu_vec1 and covariance matrix cov_mat1

In [ ]:
df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1
## This code creates a Pandas DataFrame (df) using the samples from class1_sample. It has three columns ('feature1', 'feature2', 'feature3') representing different features, and a new column 'target' is added with all values set to 1. This 'target' column is often used in machine learning to represent the class label (in this case, class 1)
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)
## Similar to the first set of samples, this code generates another set of 20 samples (class2_sample) with a different mean vector (mu_vec2) and covariance matrix (cov_mat2). Another DataFrame (df1) is created with the same features but a 'target' column with all values set to 0.

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = df.append(df1,ignore_index=True)

df = df.sample(40)
     ## This line appends the rows of df1 to df to create a single DataFrame with 40 samples. The ignore_index=True parameter reindexes the resulting DataFrame.

df.head()

<ipython-input-4-055ae4ee6360>:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df1,ignore_index=True)


feature1  feature2  feature3  target
2  -0.367548 -1.137460 -0.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620  0.928676       1
11  1.968435 -0.547788  0.320582       1
12 -2.506230  0.146960  1.606195       1

from matplotlib import pyplot as plt
_df_0['feature1'].plot(kind='hist', bins=20, title='feature1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['feature2'].plot(kind='hist', bins=20, title='feature2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['feature3'].plot(kind='hist', bins=20, title='feature3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['target'].plot(kind='hist', bins=20, title='target')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='feature1', y='feature2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='feature2', y='feature3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='feature3', y='target', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7['feature1'].plot(kind='line', figsize=(8, 4), title='feature1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_8['feature2'].plot(kind='line', figsize=(8, 4), title='feature2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['feature3'].plot(kind='line', figsize=(8, 4), title='feature3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['target'].plot(kind='line', figsize=(8, 4), title='target')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:

import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()


In [ ]:

# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [ ]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[ 1.34076734  0.24528825 -0.04837916]
 [ 0.24528825  1.12566959 -0.04462773]
 [-0.04837916 -0.04462773  0.90422367]]


In [ ]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [ ]:
eigen_values

array([1.50802952, 0.96706629, 0.89556479])

In [ ]:

eigen_values

array([1.50802952, 0.96706629, 0.89556479])

In [ ]:
pc = eigen_vectors[0:2]
pc


array([[ 0.00431394, -0.55603254, -0.83114933],
       [ 0.18596179,  0.81710497, -0.54567177]])

In [ ]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()


PC1       PC2  target
0  0.898632 -0.821987       1
1 -0.686082 -1.125064       0
2 -0.998928 -0.092196       1
3  0.046628 -0.256479       1
4 -1.427515 -1.222436       1

In [ ]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

NameError: ignored